### ISSUE TITLE
Compile bug: Metal library fails to compile — block_turbo4_0 missing signs / rnorm fields referenced by quantize_turbo4_0

### ISSUE THREAD

**Issue by Hrsh-Venket** [Anbeeld/beellama.cpp#30]
### Git commit

07ac3cec6 Merge pull request #25 from chimpera/fix-argmax-topk-64 

### Operating systems

Mac

### GGML backends

Metal

### Problem description & steps to reproduce

On macOS (-DGGML_METAL=ON), the embedded Metal library fails to compile at startup because quantize_turbo4_0 and
  turbo4_dequantize_full_block in ggml/src/ggml-metal/ggml-metal.metal reference dst.signs / xb->rnorm, but block_turbo4_0 in
  ggml/src/ggml-common.h:335-339 only defines norm and qs. The Metal kernels look like turbo3 code copy-pasted under the turbo4 name — the CUDA path
  in ggml/src/ggml-cuda/turbo-quant-cuda.cuh:498 implements the correct 4-bit-only layout. Because the whole Metal library fails to build, GPU offload
   is broken for every model and cache type on macOS, not just turbo4.

### Compile command

```shell
cmake -B build -DGGML_METAL=ON -DCMAKE_BUILD_TYPE=Release && cmake --build build -j
  ./build/bin/llama-server --version
```

### Relevant log output

```shell
ggml_metal_library_init: error: Error Domain=MTLLibraryErrorDomain Code=3
  program_source:3714:49: error: no member named 'signs' in 'block_turbo4_0'
      for (int j = 0; j < QK_TURBO4 / 8; j++) dst.signs[j] = 0;
  program_source:3746:9:  error: no member named 'rnorm' in 'block_turbo4_0'; did you mean 'norm'?
      dst.rnorm = half(sqrt(rnorm_sq));
  program_source:3752:17: error: no member named 'signs' in 'block_turbo4_0'
  program_source:3859:35: error: no member named 'rnorm' in 'block_turbo4_0'
  program_source:3880:27: error: no member named 'signs' in 'block_turbo4_0'
  program_source:12896:50: error: no member named 'signs' in 'block_turbo4_0'
    ... in instantiation of kernel_set_rows_turbo<int64_t, block_turbo4_0, ...>
  ggml_metal_device_init: error: failed to create library
```

**Comment by Anbeeld** [comment]
Just pushed pre-release WIP version of v0.3.0: https://github.com/Anbeeld/beellama.cpp/tree/v0.3.0

The branch contains a full rebase to the latest llama.cpp (with MTP and upstream spec architecture), but also a lot of DFlash fixes (multi-slot, multi-GPU, speculation in tool calls, etc.)

Please build and try that branch, and report back on what's the state of the issue there. All the follow up fixes will be on v0.3.0 too, as it's a bit pointless to do patches within v0.2.0 because of upstream rebasing.

**Comment by Hrsh-Venket** [comment]
Thanks for the response @Anbeeld . I've written out the issue again here in the same format as above. I'd be happy to take this on and split turbo3 and turbo4 into two kernels for metal. Do assign it to me if you're open to contributions -- will probably fix this for myself anyway 

### Operating systems

Mac

### GGML backends

Metal

### Problem description & steps to reproduce

On macOS (`-DGGML_METAL=ON`), the embedded Metal library still fails to compile at startup. The standalone `quantize_turbo4_0` (`ggml/src/ggml-metal/ggml-metal.metal:598`) and `turbo4_dequantize_full_block` (line 731) now match the correct turbo4 layout from `block_turbo4_0` in `ggml/src/ggml-common.h:359-362` (only `norm` + `qs[64]`, no `signs`/`rnorm`) — so those errors are gone.

However, `kernel_set_rows_turbo` (line 9772) is a single generic template whose body unconditionally writes to `blk.signs[...]` at lines 9819 and 9835 — that field is turbo3-only. The template is then instantiated for both turbo3 and turbo4 at lines 10686–10689:

```cpp
template [[host_name("kernel_set_rows_turbo4_i64")]] kernel set_rows_turbo_t
    kernel_set_rows_turbo<int64_t, block_turbo4_0, QK_TURBO4, quantize_turbo4_0>;
template [[host_name("kernel_set_rows_turbo4_i32")]] kernel set_rows_turbo_t
    kernel_set_rows_turbo<int32_t, block_turbo4_0, QK_TURBO4, quantize_turbo4_0>;
```

The turbo4 instantiations can't compile against `block_turbo4_0`, and because Metal builds the entire `.metal` source as a single library, this kills *all* Metal kernels — including users who never request a TurboQuant type. The CUDA path in `ggml/src/ggml-cuda/turbo-quant-cuda.cuh` correctly separates the 3-bit and 4-bit set-rows paths; Metal needs the same split (specialize for turbo4 with packed-nibble writes to `qs` only, or refactor to call `quantize_func` instead of inlining a turbo3-shaped quantization loop).

After Metal library init fails, every probe/fallback context allocation fails, `common_fit_params` cannot measure free memory, model load aborts, and the process segfaults on shutdown.

Repro (q4_0 KV cache only — no turbo4 involved):

```
./build/bin/llama-cli -hf unsloth/Qwen3.6-27B-MTP-GGUF --spec-type mtp \
    --flash-attn on -ctk q4_0 -ctv q4_0 -c 16384
```

Hardware: Apple Silicon, macOS Darwin 25.4.0.

### First Bad Commit

_No response_ — bug is present at `200956bd1` (current `v0.3.0` HEAD). Earlier turbo4 site fixes did not cover `kernel_set_rows_turbo`.

### Compile command

```shell
cmake -B build -DGGML_METAL=ON -DCMAKE_BUILD_TYPE=Release && cmake --build build -j
./build/bin/llama-cli -hf unsloth/Qwen3.6-27B-MTP-GGUF --spec-type mtp --flash-attn on -ctk q4_0 -ctv q4_0 -c 16384
```

### Relevant log output

```shell
ggml_metal_library_init: error: Error Domain=MTLLibraryErrorDomain Code=3
program_source:12983:50: error: no member named 'signs' in 'block_turbo4_0'
    for (int j = 0; j < QK / 8; j++) blk.signs[j] = 0;
                                     ~~~ ^
program_source:13852:78: note: in instantiation of function template specialization
    'kernel_set_rows_turbo<long, block_turbo4_0, 128, &quantize_turbo4_0>' requested here
template [[host_name("kernel_set_rows_turbo4_i64")]] kernel set_rows_turbo_t
    kernel_set_rows_turbo<int64_t, block_turbo4_0, QK_TURBO4, quantize_turbo4_0>;

program_source:12999:36: error: no member named 'signs' in 'block_turbo4_0'
    if (idx & 0x4) blk.signs[j / 8] |= (1 << (j % 8));
                   ~~~ ^
program_source:13853:78: note: in instantiation of function template specialization
    'kernel_set_rows_turbo<int, block_turbo4_0, 128, &quantize_turbo4_0>' requested here
template [[host_name("kernel_set_rows_turbo4_i32")]] kernel set_rows_turbo_t
    kernel_set_rows_turbo<int32_t, block_turbo4_0, QK_TURBO4, quantize_turbo4_0>;

ggml_metal_device_init: error: failed to create library
ggml_metal_init: error: failed to initialize the Metal library
ggml_backend_metal_device_init_backend: error: failed to allocate context
llama_init_from_model: failed to initialize the context: failed to initialize MTL0 backend
srv    load_model: [spec] failed to measure MTP context memory: failed to create llama_context from model
common_fit_params: encountered an error while trying to fit params to free device memory: failed to create llama_context from model
common_init_from_params: failed to create context with model '.../Qwen3.6-27B-Q4_K_M.gguf'
Segmentation fault: 11
```

**Comment by Anbeeld** [comment]
Implemented the fix on v0.3.0, please try it.

**Comment by bIackdog** [comment]
fix on v0.3.0 does not seem to work, while I managed to complete the build, it seems to still fall back to the CPU binary, indicated by this line `beellama.cpp/ggml/src/ggml-cpu/ops.cpp:4569: fatal error`.
 

as I am not familiar with what to provide, I would like some pointers, on what logs are necessary to assist in any way possible. 

here's the run attempt log:
```
dead@MacBookPro ~ % export LLAMA_CACHE="unsloth/gemma-4-26B-A4B-it-GGUF"     
llama-server \
    -hf unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q5_K_XL \
      --mmap \
      --cache-type-k turbo4 \
      --cache-type-v turbo3 \
      -c 8192
0.10.506.855 W common_download_file_single_online: HEAD failed, status: 404
0.11.138.011 I log_info: verbosity = 3 (adjust with the `-lv N` CLI arg)
0.11.138.016 I device_info:
0.11.138.041 I   - MTL0    : Apple M1 Pro (30720 MiB, 30719 MiB free)
0.11.138.043 I   - BLAS    : Accelerate (0 MiB, 0 MiB free)
0.11.138.073 I   - CPU     : Apple M1 Pro (32768 MiB, 32768 MiB free)
0.11.139.486 I system_info: n_threads = 8 (n_threads_batch = 8) / 10 | MTL : EMBED_LIBRARY = 1 | CPU : NEON = 1 | ARM_FMA = 1 | FP16_VA = 1 | DOTPROD = 1 | LLAMAFILE = 1 | ACCELERATE = 1 | REPACK = 1 | 
0.11.139.492 I srv  llama_server: n_parallel is set to auto, using n_parallel = 4 and kv_unified = true
0.11.139.737 I srv          init: running without SSL
0.11.140.029 I srv          init: using 9 threads for HTTP server
0.11.140.466 I srv         start: binding port with default address family
0.11.141.956 I srv  llama_server: loading model
0.11.141.998 I srv    load_model: loading model 'unsloth/gemma-4-26B-A4B-it-GGUF/models--unsloth--gemma-4-26B-A4B-it-GGUF/snapshots/3365c68df1a83799b846d05324ebfadbb8cc70b3/gemma-4-26B-A4B-it-UD-Q5_K_XL.gguf'
0.11.781.152 I srv    load_model: [mtmd] estimated worst-case memory usage of mmproj is 1296.85 MiB
0.11.781.217 I common_init_result: fitting params to device memory ...
0.11.781.217 I common_init_result: (for bugs during this step try to reproduce them with -fit off, or provide --verbose logs if the bug only occurs with -fit on)
0.12.516.256 W load: control-looking token:     50 '<|tool_response>' was not control-type; this is probably a bug in the model. its type will be overridden
0.12.519.268 W load: control-looking token:    212 '</s>' was not control-type; this is probably a bug in the model. its type will be overridden
0.12.523.154 W load: control-looking token:      1 '<eos>' was not control-type; this is probably a bug in the model. its type will be overridden
0.12.526.873 W load: special_eog_ids contains '<|tool_response>', removing '</s>' token from EOG list
0.19.680.175 W llama_context: n_ctx_seq (8192) < n_ctx_train (262144) -- the full capacity of the model will not be utilized
0.19.717.340 I common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
/Users/dead/projects/LLM/beellama.cpp/ggml/src/ggml-cpu/ops.cpp:4569: fatal error
WARNING: Using native backtrace. Set GGML_BACKTRACE_LLDB for more info.
WARNING: GGML_BACKTRACE_LLDB may cause native MacOS Terminal.app to crash.
See: https://github.com/ggml-org/llama.cpp/pull/17869
0   libggml-base.0.13.0.dylib           0x000000010355128c ggml_print_backtrace + 276
1   libggml-base.0.13.0.dylib           0x0000000103551478 ggml_abort + 156
2   libggml-cpu.0.13.0.dylib            0x000000010303e4b4 ggml_compute_forward_scale + 416
3   libggml-cpu.0.13.0.dylib            0x0000000102fdc4d4 ggml_graph_compute_thread + 1320
4   libggml-cpu.0.13.0.dylib            0x0000000102fdbbd4 ggml_graph_compute + 432
5   libggml-cpu.0.13.0.dylib            0x0000000102fdecc0 _ZL30ggml_backend_cpu_graph_computeP12ggml_backendP11ggml_cgraph + 120
6   libggml-base.0.13.0.dylib           0x00000001035713e8 ggml_backend_sched_graph_compute_async + 2328
7   libllama.0.0.9868.dylib             0x00000001032c2d50 _ZN13llama_context13graph_computeEP11ggml_cgraphb + 164
8   libllama.0.0.9868.dylib             0x00000001032c2b0c _ZN13llama_context14process_ubatchERK12llama_ubatch14llm_graph_typeP22llama_memory_context_iR11ggml_status + 324
9   libllama.0.0.9868.dylib             0x00000001032c6080 _ZN13llama_context6decodeERK11llama_batch + 9272
10  libllama.0.0.9868.dylib             0x00000001032cda40 llama_decode + 20
11  libllama-common.0.0.9868.dylib      0x000000010425cf30 _Z23common_init_from_paramsR13common_paramsb + 1872
12  libllama-server-impl.dylib          0x0000000103974184 _ZN19server_context_impl10load_modelER13common_params + 3204
13  libllama-server-impl.dylib          0x00000001038ad0b8 _Z12llama_serveriPPc + 15608
14  dyld                                0x000000018350be00 start + 6992
zsh: abort      llama-server -hf unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q5_K_XL --mmap  turbo4  
```
OS: MacOS 26.5

**Comment by Anbeeld** [comment]
Fixed this and a number of other issues with Mac builds. Currently v0.3.0 has GitHub CI/CD successfully producing the build, so you can try it as prebuilt or Docker as well. Please check it out and report back.

**Comment by bIackdog** [comment]
Build indeed succeeds now and runs

Though when using turboquant, server now crashes on load. Here's log:
```
dead@Mykhailos-MBP bin % export LLAMA_CACHE="unsloth/gemma-4-26B-A4B-it-GGUF"
./llama-server \
    -hf unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q5_K_XL \
    --chat-template-kwargs '{"enable_thinking":false}' \
    -c 8192 \
    --cache-type-k turbo4 --cache-type-v turbo3_tcq

0.10.604.312 W Setting 'enable_thinking' via --chat-template-kwargs is deprecated. Use --reasoning on / --reasoning off instead.
0.11.123.764 W common_download_file_single_online: HEAD failed, status: 404
0.12.031.831 I log_info: verbosity = 3 (adjust with the `-lv N` CLI arg)
0.12.031.837 I device_info:
0.12.031.864 I   - MTL0    : Apple M1 Pro (30720 MiB, 30719 MiB free)
0.12.031.866 I   - BLAS    : Accelerate (0 MiB, 0 MiB free)
0.12.031.899 I   - CPU     : Apple M1 Pro (32768 MiB, 32768 MiB free)
0.12.031.947 I system_info: n_threads = 8 (n_threads_batch = 8) / 10 | MTL : EMBED_LIBRARY = 1 | CPU : NEON = 1 | ARM_FMA = 1 | FP16_VA = 1 | DOTPROD = 1 | LLAMAFILE = 1 | ACCELERATE = 1 | REPACK = 1 | 
0.12.031.952 I srv  llama_server: n_parallel is set to auto, using n_parallel = 4 and kv_unified = true
0.12.031.998 I srv          init: running without SSL
0.12.032.383 I srv          init: using 9 threads for HTTP server
0.12.032.550 I srv         start: binding port with default address family
0.12.033.966 I srv  llama_server: loading model
0.12.033.979 I srv    load_model: loading model 'unsloth/gemma-4-26B-A4B-it-GGUF/models--unsloth--gemma-4-26B-A4B-it-GGUF/snapshots/3365c68df1a83799b846d05324ebfadbb8cc70b3/gemma-4-26B-A4B-it-UD-Q5_K_XL.gguf'
0.12.638.399 I srv    load_model: [mtmd] estimated worst-case memory usage of mmproj is 1296.85 MiB
0.12.638.418 I common_init_result: fitting params to device memory ...
0.12.638.418 I common_init_result: (for bugs during this step try to reproduce them with -fit off, or provide --verbose logs if the bug only occurs with -fit on)
/Users/dead/projects/LLM/beellama.cpp/ggml/src/ggml-backend.cpp:898: pre-allocated tensor (cache_v_l0 (view)) in a buffer (MTL0) that cannot run the operation (SET_ROWS)
WARNING: Using native backtrace. Set GGML_BACKTRACE_LLDB for more info.
WARNING: GGML_BACKTRACE_LLDB may cause native MacOS Terminal.app to crash.
See: https://github.com/ggml-org/llama.cpp/pull/17869
0   libggml-base.0.13.1.dylib           0x0000000100a61458 ggml_print_backtrace + 276
1   libggml-base.0.13.1.dylib           0x0000000100a61644 ggml_abort + 156
2   libggml-base.0.13.1.dylib           0x0000000100a7fb84 _ZL38ggml_backend_sched_backend_id_from_curP18ggml_backend_schedP11ggml_tensor + 952
3   libggml-base.0.13.1.dylib           0x0000000100a7d940 ggml_backend_sched_split_graph + 452
4   libllama.0.0.10026.dylib            0x00000001007b4f40 _ZN13llama_context13graph_reserveEjjjPK22llama_memory_context_ibPm + 524
5   libllama.0.0.10026.dylib            0x00000001007b3958 _ZN13llama_context13sched_reserveEv + 1052
6   libllama.0.0.10026.dylib            0x00000001007b2498 _ZN13llama_contextC2ERK11llama_model20llama_context_params + 5012
7   libllama.0.0.10026.dylib            0x00000001007cee18 llama_init_from_model + 744
8   libllama-common.0.0.10026.dylib     0x0000000101785674 _Z29common_get_device_memory_dataPKcPK18llama_model_paramsPK20llama_context_paramsRNSt3__16vectorIP19ggml_backend_deviceNS7_9allocatorISA_EEEERjSF_SF_14ggml_log_level + 236
9   libllama-common.0.0.10026.dylib     0x0000000101787c64 _ZL22common_params_fit_implPKcP18llama_model_paramsP20llama_context_paramsPfP32llama_model_tensor_buft_overridePmj14ggml_log_level + 180
10  libllama-common.0.0.10026.dylib     0x0000000101787a08 _Z17common_fit_paramsPKcP18llama_model_paramsP20llama_context_paramsPfP32llama_model_tensor_buft_overridePmj14ggml_log_level + 108
11  libllama-common.0.0.10026.dylib     0x0000000101766fcc _ZN18common_init_resultC2ER13common_paramsb + 288
12  libllama-common.0.0.10026.dylib     0x0000000101768510 _Z23common_init_from_paramsR13common_paramsb + 68
13  libllama-server-impl.dylib          0x0000000100e76e84 _ZN19server_context_impl10load_modelER13common_params + 3932
14  libllama-server-impl.dylib          0x0000000100daf460 _Z12llama_serveriPPc + 15608
15  dyld                                0x000000018350be00 start + 6992
zsh: abort      ./llama-server -hf unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q5_K_XL   -c 8192    
```

this is log from the instance I built myself. When looking for a docker image, I could not find v0.3.0 for arm64 backend

**Comment by Anbeeld** [comment]
TCQ is not supported on Metal IIRC (yet), have you tried it with plain turbo and non-turbo types?

**Comment by bIackdog** [comment]
Plain turbo types and no kv cache compression works. Will try to check DFlash next. 
Sorry for the late response, had a long weekend :)

**Comment by bIackdog** [comment]
```
66.57.420.204 I slot   operator(): id  0 | task 16 | adaptive dm profit: cur=0 recommended=4 score=28.2 action=apply
WARNING: Using native backtrace. Set GGML_BACKTRACE_LLDB for more info.
WARNING: GGML_BACKTRACE_LLDB may cause native MacOS Terminal.app to crash.
See: https://github.com/ggml-org/llama.cpp/pull/17869
0   libggml-base.0.13.1.dylib           0x000000010566e2c0 ggml_print_backtrace + 276
1   libggml-base.0.13.1.dylib           0x0000000105684ef4 _ZL23ggml_uncaught_exceptionv + 12
2   libc++abi.dylib                     0x000000018387d75c _ZSt11__terminatePFvvE + 16
3   libc++abi.dylib                     0x000000018387fbe4 __cxa_get_exception_ptr + 0
4   libc++abi.dylib                     0x000000018386c09c __cxa_get_globals + 0
5   libllama.0.0.10096.dylib            0x0000000105395898 _ZNSt3__120__throw_out_of_rangeB8ue170006EPKc + 60
6   libllama.0.0.10096.dylib            0x000000010547feb4 _ZNKSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEiEENS_22__unordered_map_hasherIS7_S8_NS_4hashIS7_EENS_8equal_toIS7_EELb1EEENS_21__unordered_map_equalIS7_S8_SD_SB_Lb1EEENS5_IS8_EEE4findIS7_EENS_21__hash_const_iteratorIPNS_11__hash_nodeIS8_PvEEEERKT_ + 0
7   libllama.0.0.10096.dylib            0x0000000105477750 _ZNK11llama_vocab4impl14token_to_pieceEiPciib + 1300
8   libllama-common.0.0.10096.dylib     0x0000000106e449a0 _Z21common_token_to_piecePK11llama_vocabib + 112
9   libllama-server-impl.dylib          0x0000000105ff974c _ZN19server_context_impl12update_slotsEv + 46548
10  libllama-server-impl.dylib          0x0000000105fb72d8 _ZN12server_queue10start_loopEx + 500
11  libllama-server-impl.dylib          0x0000000105f0a218 _Z12llama_serveriPPc + 16656
12  dyld                                0x000000018350be00 start + 6992
libc++abi: terminating due to uncaught exception of type std::out_of_range: vector
zsh: abort      llama-server -hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF --spec-type dflash    all  
```
dflash seems to crash the server after a first token. Attempting DFlash with Gemma-4-26B-A4B 
```
export LLAMA_CACHE="unsloth/gemma-4-26B-A4B-it-GGUF"   
llama-server \
    -hf unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q5_K_XL \
    --spec-type dflash \                                
    --spec-draft-model ~/.llama-cpp/gemma4-26b-a4b-it-dflash-Q5_K_M.gguf \
    --spec-draft-ngl all \
    --chat-template-kwargs '{"enable_thinking":false}' \
    -c 8192 \
```
resulted in model giving out `<unused50>` as a response, log says:
```
0.22.340.866 I slot   operator(): id  0 | task 0 | adaptive dm profit: cur=0 recommended=4 score=25.9 action=apply
0.22.375.459 E dflash: invalid reduced-logits token -1 in draft at row=1/5 (top_k=1 committed=19 cross_len=19 ring_filled=19 ring_write_pos=19 gpu_ring=0 cpu_ring_valid=1 invalid_reduced_logits_streak=1 score=0 spec=-1 offset=0)
0.22.432.516 E dflash: invalid reduced-logits token -1 in draft at row=1/5 (top_k=1 committed=20 cross_len=20 ring_filled=20 ring_write_pos=20 gpu_ring=0 cpu_ring_valid=1 invalid_reduced_logits_streak=2 score=0 spec=-1 offset=0)
0.22.489.031 E dflash: invalid reduced-logits token -1 in draft at row=1/5 (top_k=1 committed=21 cross_len=21 ring_filled=21 ring_write_pos=21 gpu_ring=0 cpu_ring_valid=1 invalid_reduced_logits_streak=3 score=0 spec=-1 offset=0)
0.22.545.852 E dflash: invalid reduced-logits token -1 in draft at row=1/5 (top_k=1 committed=22 cross_len=22 ring_filled=22 ring_write_pos=22 gpu_ring=0 cpu_ring_valid=1 invalid_reduced_logits_streak=4 score=0 spec=-1 offset=0)
0.22.545.854 E dflash: fail-closed after 4 consecutive invalid reduced-logits drafts; skipping DFlash drafting until the cross-ring state is reset
0.25.934.915 W srv          stop: cancel task, id_task = 0
0.25.973.397 I slot process_sing: id  0 | task 0 | adaptive dm: reset state for canceled task
0.25.973.402 I slot      release: id  0 | task 0 | stop processing: n_tokens = 113, truncated = 0
0.25.973.406 I srv  update_slots: all slots are idle
```
used your dflash models for both qwen and Gemma
can't say if I screwed something up or it just doesn't work
used latest v0.3.1 build

**Comment by Anbeeld** [comment]
Starting with v0.4.0, BeeLlama uses upstream implementation for DFlash, with some adjustments on top of it.
TurboQuant is not supported anymore as well.
Closing this issue as it's relevant only for pre-v0.4.0.
