### ISSUE TITLE
Compile bug: LOG_DBG error

### ISSUE THREAD

**Issue by jhughes2112** [Anbeeld/beellama.cpp#8]
### Git commit

HEAD and previous two commits
git clone --filter=blob:none https://github.com/Anbeeld/beellama.cpp.git . && git checkout a6690f497b200ca39f6bdf8feceedd706a386e26

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

I tried building today.  Seems like there is some header not being included that defines the logging macro.  

### First Bad Commit

Have not found a good commit yet to build from.

### Compile command

```shell
Here's my build line (inside a linux docker container):

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF \
    -DGGML_CUDA=ON \
    -DGGML_NATIVE=ON \
    -DGGML_CUDA_FA=ON \
    -DGGML_CUDA_FA_ALL_QUANTS=ON \
    -DLLAMA_CURL=OFF \
    -DCMAKE_CUDA_ARCHITECTURES="75"
```

### Relevant log output

```shell
1438.3 [ 77%] Building CXX object tests/CMakeFiles/test-adaptive-dm.dir/test-adaptive-dm.cpp.o
1438.9 In file included from /build/tests/test-adaptive-dm.cpp:1:
1438.9 /build/tests/../tools/server/server-adaptive-dm.h: In member function ‘void server_adaptive_dm_state::observe_profit_timing(int, float, float, float, float)’:
1438.9 /build/tests/../tools/server/server-adaptive-dm.h:418:17: error: ‘LOG_DBG’ was not declared in this scope
1438.9   418 |                 LOG_DBG("observe_profit_timing: n_draft=%d >= PROFIT_DEPTHS=%d, "
1438.9       |                 ^~~~~~~
```
